---
# These variables can be overridden in distribution files.

# Dependencies required to install Buildbot
buildbot_deps:
  - python-pip # So we can install Python modules

# Dependencies required to download files
fetch_deps:
  - git
  - wget # For acutil/fetch-params.sh

# Dependencies required to configure AnimeCoin
conf_deps:
  - autoconf
  - automake
  - m4

# Dependencies required to compile AnimeCoin
build_deps:
  - g++
  - gcc
  - make

# Dependencies required to link AnimeCoin
link_deps:
  - libtool

# Additional distribution-specific dependencies
dist_deps: []

# Additional grind-specific dependencies
grind_deps:
  - lcov
  - valgrind

# Python modules required for a AnimeCoin Buildbot worker
buildbot_modules:
  - pip # Needs to be updated first so Buildbot installs
  - buildbot-worker
  - pyflakes

# Python modules required to run the AnimeCoin RPC test suite
rpc_test_modules:
  - pyblake2
  - pyzmq

# Environment variables
pip_bin_dir: /usr/local/bin
